name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check location
      run: pwd

    - uses: actions/checkout@v3
    
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v4.1.8
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        REMOTE_HOST: "ec2-13-215-158-39.ap-southeast-1.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/var/www/html/aws-drupal"
