<?php

/**
 * @file
 * Functions to support theming in the ThoTrang Web Theme theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function thotrang_web_theme_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function thotrang_web_theme_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function thotrang_web_theme_preprocess_node(&$variables) {

}
